parameters:
#    skautis.example.class: Jinora\SkautisBundle\Example

services:
#    skautis.example:
#        class: %skautis.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
